"""Library card costs updated to str nullable

Revision ID: 07c590574c8d
Revises: da86d1f0323e
Create Date: 2026-06-16 13:30:26.724252

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "07c590574c8d"
down_revision: str | Sequence[str] | None = "da86d1f0323e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "library", "pool_cost", existing_type=sa.INTEGER(), type_=sa.String(), nullable=True
    )
    op.alter_column(
        "library", "blood_cost", existing_type=sa.INTEGER(), type_=sa.String(), nullable=True
    )
    op.alter_column(
        "library", "conviction_cost", existing_type=sa.INTEGER(), type_=sa.String(), nullable=True
    )
    op.drop_column("library", "capacity")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "library", sa.Column("capacity", sa.INTEGER(), autoincrement=False, nullable=False)
    )
    op.alter_column(
        "library", "conviction_cost", existing_type=sa.String(), type_=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "library", "blood_cost", existing_type=sa.String(), type_=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "library", "pool_cost", existing_type=sa.String(), type_=sa.INTEGER(), nullable=False
    )
    # ### end Alembic commands ###
