"""Adding VTES Cards&Set tables

Revision ID: 25cd7e703ee6
Revises: 6d46f791da8b
Create Date: 2026-06-15 17:12:52.774382

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "25cd7e703ee6"
down_revision: str | Sequence[str] | None = "6d46f791da8b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("release_date", sa.Date(), nullable=False),
        sa.Column("full_name", sa.String(), nullable=False),
        sa.Column("abbrev", sa.String(), nullable=False),
        sa.Column("company", sa.String(), nullable=False),
        sa.CheckConstraint("id >= 300001 AND id <= 399999", name="ck_sets_id_range"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_sets_full_name"), "sets", ["full_name"], unique=False)
    op.create_table(
        "crypt",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("clan", sa.String(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("artist", sa.String(), nullable=False),
        sa.Column("group", sa.String(), nullable=False),
        sa.Column("capacity", sa.Integer(), nullable=False),
        sa.Column("path", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("disciplines", sa.String(), nullable=False),
        sa.Column("card_text", sa.String(), nullable=False),
        sa.Column("banned", sa.Boolean(), nullable=False),
        sa.Column("adv", sa.Boolean(), nullable=False),
        sa.Column("set_id", sa.Integer(), nullable=False),
        sa.CheckConstraint("id >= 100001 AND id <= 199999", name="ck_crypt_id_range"),
        sa.ForeignKeyConstraint(
            ["set_id"],
            ["sets.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_crypt_clan"), "crypt", ["clan"], unique=False)
    op.create_index(op.f("ix_crypt_name"), "crypt", ["name"], unique=False)
    op.create_table(
        "library",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("artist", sa.String(), nullable=False),
        sa.Column("capacity", sa.Integer(), nullable=False),
        sa.Column("pool_cost", sa.Integer(), nullable=False),
        sa.Column("blood_cost", sa.Integer(), nullable=False),
        sa.Column("conviction_cost", sa.Integer(), nullable=False),
        sa.Column("clan", sa.String(), nullable=False),
        sa.Column("path", sa.String(), nullable=False),
        sa.Column("requirement", sa.String(), nullable=False),
        sa.Column("flavor_text", sa.String(), nullable=False),
        sa.Column("card_text", sa.String(), nullable=False),
        sa.Column("discipline", sa.String(), nullable=False),
        sa.Column("banned", sa.Boolean(), nullable=False),
        sa.Column("burn_option", sa.Boolean(), nullable=False),
        sa.Column("set_id", sa.Integer(), nullable=False),
        sa.CheckConstraint("id >= 200001 AND id <= 299999", name="ck_library_id_range"),
        sa.ForeignKeyConstraint(
            ["set_id"],
            ["sets.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_library_clan"), "library", ["clan"], unique=False)
    op.create_index(op.f("ix_library_name"), "library", ["name"], unique=False)
    op.create_index(op.f("ix_library_type"), "library", ["type"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_library_type"), table_name="library")
    op.drop_index(op.f("ix_library_name"), table_name="library")
    op.drop_index(op.f("ix_library_clan"), table_name="library")
    op.drop_table("library")
    op.drop_index(op.f("ix_crypt_name"), table_name="crypt")
    op.drop_index(op.f("ix_crypt_clan"), table_name="crypt")
    op.drop_table("crypt")
    op.drop_index(op.f("ix_sets_full_name"), table_name="sets")
    op.drop_table("sets")
    # ### end Alembic commands ###
