"""Fix: accidentaly removed capacity columns

Revision ID: 432c92870e3a
Revises: 07c590574c8d
Create Date: 2026-06-16 13:53:22.078896

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "432c92870e3a"
down_revision: str | Sequence[str] | None = "07c590574c8d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("library", sa.Column("capacity", sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("library", "capacity")
    # ### end Alembic commands ###
