"""add tournament deck tables

Revision ID: ca977c9dc0a7
Revises: cb06de418c1f
Create Date: 2026-06-18 11:49:10.899445

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ca977c9dc0a7"
down_revision: str | Sequence[str] | None = "cb06de418c1f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tournaments",
        sa.Column("event_id", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("location", sa.String(), nullable=False),
        sa.Column("date_start", sa.Date(), nullable=False),
        sa.Column("date_end", sa.Date(), nullable=True),
        sa.Column("rounds_format", sa.String(), nullable=False),
        sa.Column("players_count", sa.Integer(), nullable=False),
        sa.Column("winner", sa.String(), nullable=False),
        sa.Column("vekn_number", sa.Integer(), nullable=True),
        sa.Column("event_url", sa.String(), nullable=False),
        sa.Column("forum_post_url", sa.String(), nullable=True),
        sa.Column("vp_comment", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("event_id"),
    )
    op.create_index(op.f("ix_tournaments_date_start"), "tournaments", ["date_start"], unique=False)
    op.create_index(op.f("ix_tournaments_name"), "tournaments", ["name"], unique=False)
    op.create_table(
        "decks",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tournament_event_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("created_by", sa.String(), nullable=True),
        sa.Column("description", sa.String(), server_default="", nullable=False),
        sa.Column("crypt_count", sa.Integer(), nullable=False),
        sa.Column("crypt_min", sa.Integer(), nullable=False),
        sa.Column("crypt_max", sa.Integer(), nullable=False),
        sa.Column("crypt_avg", sa.Float(), nullable=False),
        sa.Column("library_count", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tournament_event_id"], ["tournaments.event_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_decks_tournament_event_id"), "decks", ["tournament_event_id"], unique=True
    )
    op.create_table(
        "deck_crypt_cards",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("deck_id", sa.UUID(), nullable=False),
        sa.Column("count", sa.Integer(), nullable=False),
        sa.Column("raw_name", sa.String(), nullable=False),
        sa.Column("raw_grouping", sa.Integer(), nullable=False),
        sa.Column("crypt_card_id", sa.Integer(), nullable=True),
        sa.Column("crypt_card_group", sa.String(), nullable=True),
        sa.Column("crypt_card_adv", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["crypt_card_id", "crypt_card_group", "crypt_card_adv"],
            ["crypt.id", "crypt.group", "crypt.adv"],
            name="fk_deck_crypt_cards_crypt",
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(["deck_id"], ["decks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_deck_crypt_cards_crypt",
        "deck_crypt_cards",
        ["crypt_card_id", "crypt_card_group", "crypt_card_adv"],
        unique=False,
    )
    op.create_index(
        op.f("ix_deck_crypt_cards_deck_id"), "deck_crypt_cards", ["deck_id"], unique=False
    )
    op.create_table(
        "deck_library_cards",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("deck_id", sa.UUID(), nullable=False),
        sa.Column("section", sa.String(), nullable=False),
        sa.Column("count", sa.Integer(), nullable=False),
        sa.Column("raw_name", sa.String(), nullable=False),
        sa.Column("library_card_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["deck_id"], ["decks.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["library_card_id"], ["library.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_deck_library_cards_deck_id"), "deck_library_cards", ["deck_id"], unique=False
    )
    op.create_index(
        op.f("ix_deck_library_cards_library_card_id"),
        "deck_library_cards",
        ["library_card_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_deck_library_cards_library_card_id"), table_name="deck_library_cards")
    op.drop_index(op.f("ix_deck_library_cards_deck_id"), table_name="deck_library_cards")
    op.drop_table("deck_library_cards")
    op.drop_index(op.f("ix_deck_crypt_cards_deck_id"), table_name="deck_crypt_cards")
    op.drop_index("ix_deck_crypt_cards_crypt", table_name="deck_crypt_cards")
    op.drop_table("deck_crypt_cards")
    op.drop_index(op.f("ix_decks_tournament_event_id"), table_name="decks")
    op.drop_table("decks")
    op.drop_index(op.f("ix_tournaments_name"), table_name="tournaments")
    op.drop_index(op.f("ix_tournaments_date_start"), table_name="tournaments")
    op.drop_table("tournaments")
    # ### end Alembic commands ###
