"""Updating sets-cards relationship: now many-to-many

Revision ID: dc60f8c14be4
Revises: 25cd7e703ee6
Create Date: 2026-06-16 11:55:06.641119

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "dc60f8c14be4"
down_revision: str | Sequence[str] | None = "25cd7e703ee6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "crypt_card_sets",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("crypt_card_id", sa.Integer(), nullable=False),
        sa.Column("set_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["crypt_card_id"], ["crypt.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["set_id"], ["sets.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("crypt_card_id", "set_id", name="uq_crypt_card_sets"),
    )
    op.create_index(
        op.f("ix_crypt_card_sets_crypt_card_id"), "crypt_card_sets", ["crypt_card_id"], unique=False
    )
    op.create_index(op.f("ix_crypt_card_sets_set_id"), "crypt_card_sets", ["set_id"], unique=False)
    op.create_table(
        "library_card_sets",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("library_card_id", sa.Integer(), nullable=False),
        sa.Column("set_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["library_card_id"], ["library.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["set_id"], ["sets.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("library_card_id", "set_id", name="uq_library_card_sets"),
    )
    op.create_index(
        op.f("ix_library_card_sets_library_card_id"),
        "library_card_sets",
        ["library_card_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_library_card_sets_set_id"), "library_card_sets", ["set_id"], unique=False
    )
    op.drop_constraint(op.f("crypt_set_id_fkey"), "crypt", type_="foreignkey")
    op.drop_column("crypt", "set_id")
    op.drop_constraint(op.f("library_set_id_fkey"), "library", type_="foreignkey")
    op.drop_column("library", "set_id")
    op.alter_column("sets", "release_date", existing_type=sa.DATE(), nullable=True)
    op.create_index(op.f("ix_sets_abbrev"), "sets", ["abbrev"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_sets_abbrev"), table_name="sets")
    op.alter_column("sets", "release_date", existing_type=sa.DATE(), nullable=False)
    op.add_column("library", sa.Column("set_id", sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f("library_set_id_fkey"), "library", "sets", ["set_id"], ["id"])
    op.add_column("crypt", sa.Column("set_id", sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f("crypt_set_id_fkey"), "crypt", "sets", ["set_id"], ["id"])
    op.drop_index(op.f("ix_library_card_sets_set_id"), table_name="library_card_sets")
    op.drop_index(op.f("ix_library_card_sets_library_card_id"), table_name="library_card_sets")
    op.drop_table("library_card_sets")
    op.drop_index(op.f("ix_crypt_card_sets_set_id"), table_name="crypt_card_sets")
    op.drop_index(op.f("ix_crypt_card_sets_crypt_card_id"), table_name="crypt_card_sets")
    op.drop_table("crypt_card_sets")
    # ### end Alembic commands ###
